### ISSUE TITLE
findFirstVisibleItemPosition

### ISSUE THREAD

**Issue by SkillCollege** [Azoft/CarouselLayoutManager#1]
Can provide findFirstVisibleItemPosition(),findLastVisibleItemPosition() method or provide a listener notify which item selected now ?

**Comment by mig35** [comment]
Hi SkillCollege.
Please find new functions in this commit: 488e01b7cf83142064ac7c59e05101cd24e1d2db

**Comment by SkillCollege** [comment]
when I used new commit for new functions, I find that the RecyclerView Adapter's notifyItemChanged method did not worked. and when I used the smoothScrollToPosition method did not infinite. the scrollToPosion method is infinite. how can to solve this?

**Comment by mig35** [comment]
Hi SkillCollege.
Thanks for you bug report. Issues were confirmed. We will update lib asap.

**Comment by mig35** [comment]
fixed in: compile 'com.azoft.carousellayoutmanager:carousel:1.0.1'
