### ISSUE TITLE
item z index not Observe 

### ISSUE THREAD

**Issue by jriporter** [Azoft/CarouselLayoutManager#10]
HORIZONTAL Recyclerview have 2 item and item place on each other 
code : 
` layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());
                recyclerview_transfer.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewsUtil.dpToPx(250)));
                recyclerview_transfer.setLayoutManager(layoutManager);
                recyclerview_transfer.setHasFixedSize(true);
                recyclerview_transfer.addOnScrollListener(new CenterScrollListener());`

**Comment by mig35** [comment]
Can you add more description here? Not sure what do you mean.

**Comment by engzico** [comment]
Hi

i have same problem, it is fine on marshmallow and lollipop i suppose, but with version lower like jellybean or kitkat it is overlapping, can you please advice on that

**Comment by azoft-dev-team** [comment]
Hi @jriporter @engzico 
Fixed. Upload new version: 1.1.5
