### ISSUE TITLE
 Fatal Exception: java.lang.NullPointerException Attempt to read from field 'androidx.recyclerview.widget.RecyclerView$ViewFlinger androidx.recyclerview.widget.RecyclerView.mViewFlinger' on a null object reference

### ISSUE THREAD

**Issue by Iamkjn22** [Azoft/CarouselLayoutManager#107]
androidx.recyclerview.widget.RecyclerView$SmoothScroller.start (RecyclerView.java:11541)
androidx.recyclerview.widget.RecyclerView$LayoutManager.startSmoothScroll (RecyclerView.java:8204)
com.azoft.carousellayoutmanager.CarouselLayoutManager.smoothScrollToPosition (CarouselLayoutManager.java:210)
androidx.recyclerview.widget.RecyclerView.smoothScrollToPosition (RecyclerView.java:1781)
com.juvi.trending.TrendingFragment$2$1.run (TrendingFragment.java:162)
java.util.TimerThread.mainLoop (Timer.java:562)
java.util.TimerThread.run (Timer.java:512)

**Comment by mig35** [comment]
hey @lamkjn22,
please check your code - seems like a problem is there or inside RecyclerView.
Please check stackoverflow for this issue

**Comment by Iamkjn22** [comment]
I checked twice in my code but there is no hint for search this issue can you please help me to rid out of it?

**Comment by mig35** [comment]
but I can do nothing too. As I can see the entry point is in TrendingFragment. that calls smoothScrollToPosition. And the crash is inside RecyclerView.
So nothing to do in my side.

If you can - debug it and create PR that will fix the issue, I will appreciate this.

**Comment by mig35** [comment]
Are you sure that you are doing this on the main thread?
Again, this is not a library issue, I'm sure.
