### ISSUE TITLE
I have just added to the project nothing is displaying.

### ISSUE THREAD

**Issue by vishuhm911** [Azoft/CarouselLayoutManager#11]

**Comment by vishuhm911** [comment]
I am not getting any error also.

I have recycler view, inside cardviews are there, i have ten items in side that.

**Comment by azoft-dev-team** [comment]
Could you please provide your code and layout.xml? Try to run sample app and do it like there. Maybe you have an error in your code? Replace CarouselLayoutManager to LinearLayoutManager... is anything displaying?

**Comment by vishuhm911** [comment]
Thanks for your reply, 

I just tried another libray available in GitHub and it is working.

Thank you.

**Comment by ram992** [comment]
Hello @azoft-dev-team I happened to have the same problem
I have used the linearLayoutManager on my RecyclerView and it was working fine
But if I change the layout manager to your one the child of the recyclerView is not being displaying
There are textViews and imageViews above and below the recyclerView, which are being inflated but the recyclerView doesn't inflate

Can you help with this situation

**Comment by mig35** [comment]
@ram992 check that you have match_parent or explicit size in the layout.
