### ISSUE TITLE
Consider migrating from jcenter

### ISSUE THREAD

**Issue by TheFaithOne** [Azoft/CarouselLayoutManager#110]
Jfrog is going to deprecate and disable jcenter services - artifact migration will be needed

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by mig35** [comment]
I saw this, but I still don't understand what should be done by me.
Do you have any guide? @TheFaithOne

**Comment by TheFaithOne** [comment]
Hi there, I'm by no means an expert in this, but here's couple of articles I found online. Hope they're helpful.
https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/
https://blog.sonatype.com/what-publishers-need-to-know-about-migrating-from-jcenter-/-bintray-to-the-central-repository

**Comment by givver** [comment]
Android Studio is now complaining that jcenter is at end of its life and will stop working soon.  Please move it over mavenCentral or google.  This is a good guild.  https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

**Comment by mig35** [comment]
It will be republished soon, but with an other package id

**Comment by mig35** [comment]
now available here https://search.maven.org/artifact/com.mig35/carousellayoutmanager/1.4.6/jar
