### ISSUE TITLE
All items can be in a position from top to bottom

### ISSUE THREAD

**Issue by AnvarbekKuvandikov** [Azoft/CarouselLayoutManager#111]
Hi, I tried this. very nice.
I have a question:  is it possible for all items to  in a position from top to bottom.
![image](https://user-images.githubusercontent.com/26444968/108502911-5e434700-72d5-11eb-941d-4156a3ec4384.png)

**Comment by mig35** [comment]
hey @AnvarbekKuvandikov 
you can create your own Zooming algorithm.
Check this class and setup your implementation.
https://github.com/Azoft/CarouselLayoutManager/blob/master/CarouselLayoutManager/carousel/src/main/java/com/azoft/carousellayoutmanager/CarouselZoomPostLayoutListener.java

**Comment by mig35** [comment]
btw you will also have to change items elevation field, but this is not what library will do for you
