### ISSUE TITLE
How to disable smoothScrollToPosition

### ISSUE THREAD

**Issue by isarYMB** [Azoft/CarouselLayoutManager#116]
I want to disable smoothScrollToPosition for sliding next picture. i just want to using scrollToPosition, so that the sliding not using animation. Or i want to sensitive scroll (0 distance scroll), if I scroll, it goes directly to the next image (always center)

**Comment by mig35** [comment]
hey @isarYMB you can try to change `CenterScrollListener` implementation and make it whatever you want.

**Comment by isarYMB** [comment]
yes, im using CenterScrollListener , but the sliding have distance scroll. i want to using this carousel for 3D degree image for product in E-commerce. i want if i scrolling, the carousel not have distance if i scrolling. How to disable distance scroll?

**Comment by mig35** [comment]
sorry, but I don't get your idea. are you able to share an animation?
but anyway this library is distributed as is and no changes are planed.

**Comment by isarYMB** [comment]
i mean, i want to carousel for 360 degree image. example video like this https://www.youtube.com/watch?v=YsNO7LKqJcs . it is a collection of images that are in one carousel

**Comment by mig35** [comment]
You should find 360 degree library somewhere. This library has only carousel layout for RecyclerView.
Also you may have some problems with touch events as I can see now

**Comment by isarYMB** [comment]
i cant find 360 degree library from everywhere. so, i just can using your library. i just have 1 problem. this carousel have distance scroll for go to next picture. i want 0 distance. so that the image remains in the center and the image does not shift slightly in the other direction to go to the next image

**Comment by mig35** [comment]
You can checkout the code and adjust it for your needs 👍 
Also if you are able to make it configurable and create PR that would be awesome!

You should remove `CenterScrollListener` and `CarouselZoomPostLayoutListener` and then change some code in https://github.com/Azoft/CarouselLayoutManager/blob/master/CarouselLayoutManager/carousellayoutmanager/src/main/java/com/mig35/carousellayoutmanager/CarouselLayoutManager.java#L343

**Comment by isarYMB** [comment]
Good. finally i can solve the problem. your library is very very awesome. thankyou

**Comment by isarYMB** [comment]
and the last question. how to insert image to adapter? is there an example of the source code?
