### ISSUE TITLE
Support onClick animaton to center an item

### ISSUE THREAD

**Issue by mklimek** [Azoft/CarouselLayoutManager#12]
Hello,

Can I achieve a feature which is available on most of a carousel components implementation?
Right now if I click on an item which isn't centred (on the left or on the right) nothing happens.

What I have now is set `onClickListner` for each item in `onBindViewHolder` method.
I'd like to **animate** clicked item to a centre position somehow.

**Comment by azoft-dev-team** [comment]
Hello,

We implemented this feature in branch [feature-center_item_by_click](https://github.com/Azoft/CarouselLayoutManager/tree/feature-center_item_by_click). We will add it to the next release after small refactoring.

**Comment by mig35** [comment]
Hi, @mklimek!

Please find new 1.1.6 version with this new feature.
