### ISSUE TITLE
How to correctly offset elements?

### ISSUE THREAD

**Issue by moffpage** [Azoft/CarouselLayoutManager#121]
I need to achieve a layout like this: https://github.com/arnauddorgans/InfiniteLayout (watch Custom Layout, 3rd gif)

link: ![](https://github.com/arnauddorgans/InfiniteLayout/raw/master/custom.gif)

**Comment by mig35** [comment]
I guess you would have to make your own LL or try to tweak this one. But I'm not sure that would be an easy work @moffpage
