### ISSUE TITLE
ItemViewBinding

### ISSUE THREAD

**Issue by EasonTao** [Azoft/CarouselLayoutManager#15]
Why I can‘t find the CLASS ItemViewBinding so that many problems happened...
I'm a beginner...

example:("ItemViewBinding" is red in the following code)

private static class TestViewHolder extends RecyclerView.ViewHolder {

        private final ItemViewBinding mItemViewBinding;

        TestViewHolder(final ItemViewBinding itemViewBinding) {
            super(itemViewBinding.getRoot());

            mItemViewBinding = itemViewBinding;
        }
    }

**Comment by azoft-dev-team** [comment]
Try to rebuild project. Binding classes will be generated. How it works you can see here https://developer.android.com/topic/libraries/data-binding/index.html

**Comment by mig35** [comment]
@EasonTao , any update here?

**Comment by EasonTao** [comment]
Thank you for your help,I'v solve the problem now;
your demo is really excellent!

**Comment by ferchitas** [comment]
I continue with the same issue
