### ISSUE TITLE
Opacity of next and previous item

### ISSUE THREAD

**Issue by shaikansaar** [Azoft/CarouselLayoutManager#16]
Hi,

Thanks for the awesome library.

I've used it in my app and everything works great. However, i have a requirement to set the opacity level of next and previous item to as low as possible so that user's focus is mainly on center item. 

Please help. Thanks in advance.

Regards
Sahmed

**Comment by mig35** [comment]
Hi @shaikansaar!
You can extand CarouselZoomPostLayoutListener and add additional code there. You can change alpha (https://developer.android.com/reference/android/view/View.html#setAlpha(float)) there.
To understand CarouselZoomPostLayoutListener parameters, please look here: https://github.com/Azoft/CarouselLayoutManager/issues/4#issuecomment-226142811

If you will have any question, you can ask.
Mike

**Comment by mig35** [comment]
@shaikansaar do you have any problems?

**Comment by shaikansaar** [comment]
Hi @mig35 

Sorry for replying late.

I tried modifying the alpha values and the previous and next items opacity has been set. However, when i scroll through the items slowly the effects are not nice. I mean the during the scroll before release the item next item is highlighted/shown and this does not give good experience to user. 

Can i know your email so that i can share the video clip as i cannot attach it here?

Regards
Shaik

**Comment by mig35** [comment]
@shaikansaar you share them with this email: mig35 at mig35.com
Also, can you add your code there?

**Comment by mig35** [comment]
@shaikansaar any update?

**Comment by onka13** [comment]
```
`                if (-0.5 < itemPositionToCenterDiff && itemPositionToCenterDiff < 0.5) {
                    child.setAlpha(1f);
                } else {
                    child.setAlpha(0.5f);
                }
                return new ItemTransformation(scale, scale, translateX, translateY);`
```
