### ISSUE TITLE
Problems with proyect

### ISSUE THREAD

**Issue by Pato2790** [Azoft/CarouselLayoutManager#18]
Hello!

I want to use your carousel, but i cant do that. Have you any tutorial? 

Thank you!

Patricio from Argentina.

**Comment by mig35** [comment]
Hi @Pato2790.
If you want to use this library in your project add maven dependence 'com.azoft.carousellayoutmanager:carousel:1.1.6'.
Other things you can find in github sample directory: https://github.com/Azoft/CarouselLayoutManager/tree/master/CarouselLayoutManager/sample
