### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by Joisar** [Azoft/CarouselLayoutManager#19]
It seems good on Android.
Is there any iOS version available to have similar behaviour?
I appreciate your help on it.

Thanks,
Mehul.

**Comment by mig35** [comment]
Hi @Joisar.
In this library we used Android specific components: RecyclerView and LayoutManager. So this library available only for Android.
But you can find any other iOS alternative, like https://github.com/nicklockwood/iCarousel or any other library.
