### ISSUE TITLE
You should add a demo to reduce repeat work.

### ISSUE THREAD

**Issue by tinybright** [Azoft/CarouselLayoutManager#2]

**Comment by mig35** [comment]
Hi tinybright,
we are going to publish this project to maven, so as soon as it will be done, we will add a sample and notify you about that.

Any way you can find fully code of usage (but with no layouts and adapter classes) on the main page of this project.
Here is a copy:

// vertical and cycle layout
final CarouselLayoutManager layoutManager = new CarouselLayoutManager(CarouselLayoutManager.VERTICAL, true);
layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());// enable not center items zooming

final RecyclerView recyclerView = (RecyclerView) findViewById(R.id.recycler_view);
recyclerView.setLayoutManager(layoutManager);
recyclerView.setHasFixedSize(true); // we expect only fixed sized items for now
recyclerView.setAdapter(new TestAdapter(this)); // any adapter with any items count
recyclerView.addOnScrollListener(new CenterScrollListener()); // enable after scroll item centering

**Comment by mig35** [comment]
Find Sample project and jCenter package in this commit: 1bc217e410e0bdd8fa74634fd42576ad91d43f33
