### ISSUE TITLE
Use the SnapHelper implement center post scrolling

### ISSUE THREAD

**Issue by bluepine0808** [Azoft/CarouselLayoutManager#21]
Could you add the SnapHelper for scrolling to center?

I appreciate your help on it.
Thanks!

**Comment by mig35** [comment]
@bluepine0808 
for now we are using our custom scroll to center implementation. We will add SnapHelper, but not soon.

**Comment by bluepine0808** [comment]
Thank you for your reply！

**Comment by nishant-castleglobal** [comment]
Is there any info regarding the snap helper support ?
I wanted to use the PagerSnapHelper with this.

Thanks
