### ISSUE TITLE
can not add delete item animation?

### ISSUE THREAD

**Issue by bluepine0808** [Azoft/CarouselLayoutManager#24]
just add the animator like below, but the animateRemove is not called. Could you help this?

        recyclerView.setItemAnimator(new DefaultItemAnimator() {
            @Override
            public boolean animateRemove(RecyclerView.ViewHolder holder) {
                Log.e("carousel","animateRemove");
                return super.animateRemove(holder);
            }

            @Override
            public boolean animateAdd(RecyclerView.ViewHolder holder) {
                Log.e("carousel","animateAdd");
                return super.animateAdd(holder);
            }
        });

**Comment by mig35** [comment]
Hi @bluepine0808 
Well. Not sure why this is happening. Do you have any suggestion?

**Comment by bluepine0808** [comment]
Hi @mig35 
      I have not found the reason. Whether would you add ItemAnimator for add/remove item?

**Comment by mig35** [comment]
@bluepine0808 
I'll research this issue, but not sure when. There is no plans for custom ItemAnimator.

**Comment by mig35** [comment]
@bluepine0808 
I figure out why this is happened. When do you need a fix?

**Comment by mig35** [comment]
@bluepine0808 
please check com.azoft.carousellayoutmanager:carousel:1.1.8

**Comment by bluepine0808** [comment]
@mig35 
Thanks very much! I will try it.
