### ISSUE TITLE
How to set center item?

### ISSUE THREAD

**Issue by anik123** [Azoft/CarouselLayoutManager#25]
Is there any option/method to set center by manually(programatically)?

Please help?

Thanks in avdance.

**Comment by mig35** [comment]
@anik123 
Call RecyclerView.scrollToPosition method

**Comment by anik123** [comment]
@mig35 i am getting 

  java.lang.IllegalArgumentException: position can't be great then adapter items count. 

after using your solution.

**Comment by mig35** [comment]
@anik123 
Are you using last library version ('com.azoft.carousellayoutmanager:carousel:1.1.7')?

**Comment by anik123** [comment]
My code is :



        layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize(true);
        recyclerView.setAdapter(adapter);
        recyclerView.addOnScrollListener(new CenterScrollListener());
        recyclerView.scrollToPosition(contacts.size()-1);

**Comment by mig35** [comment]
@anik123 
have you looked what version do you use?

**Comment by anik123** [comment]
@mig35 that solve the issue. Thanks
