### ISSUE TITLE
How to change carousel parameters?

### ISSUE THREAD

**Issue by maxglu** [Azoft/CarouselLayoutManager#28]
Hi! You carousel is awesom :)
And working fine (bug with the animations turned out to be my problev, sorry).
But i have some questions:

- How to change the depth of the carousel? 
- How to change the animation speed? (Its very fast in centering)

Regards Max

**Comment by mig35** [comment]
Hi @maxglu.
I'll answer this questions tomorrow, have an other work that I have to do :)
Sorry, Mike

**Comment by nitishhhh3** [comment]
Hi @mig35 
First, thanks to develop awesome carousel.
* I have a requirement where i need to show just previous,current and next tile.It means at a time three tiles are being shown to the user.
Currently i am facing the issue where background image of a particular tile content is duplicated on an anther tile content.
All the image of the tile is being shown dynamically.

**Comment by mig35** [comment]
Hi @maxglu 
1. Do you mean how many elements are there bellow the center one? If so, you can use setMaxVisibleItems method in LayoutManager and this will make a deal. By default there are 2 elements on each side of the center item.
2. The only solution is to extend LayoutManager and change scroller (we are using standard https://developer.android.com/reference/android/support/v7/widget/LinearSmoothScroller.html)

**Comment by mig35** [comment]
Hi @nitishhhh3 
please provide an animation. can't understand you problem. perhaps this is not CarouselProblem, but your code cancellation image loading request problem. Because views are reused, so you should cancel previous loading and start a new one in onBind method of the adapter.

**Comment by maxglu** [comment]
Hi @mig35 

1. No, I meant "depth" the distance between front and rear elements. I resolve this by increase scale of all elements (except front element) in . But maybe this is wrong way. My realisation[ in gist](https://gist.github.com/maxglu/96de4fff8d304bd2f1dec7e4b49578df)
2. I try this, thanks 

And next questions - Is there an easy way to create Overscroll Effect? Like on iOS lists. 
Now i try to modify scrollBy method, and it works good, but with fast scroll i see last element in start or first element on end (like a circle carousel). 
See [my gist](https://gist.github.com/maxglu/165a2e4c003413e76baf263b64b97085)

Thank you for answers and help :)

**Comment by mig35** [comment]
@maxglu 
you can simply add this code: float increasedScale =  Math.min(1.0f, originalScale * 1.4f);
any way it is up to you to make any PostLayoutListener implementation.

**Comment by YoussefYN** [comment]
Hi @maxglu,

Please tell me how you fixed the scrolling speed, I have the same opposite problem,  the scrolling is slow and stikcy. :) 
Thanks
