### ISSUE TITLE
Distance between items

### ISSUE THREAD

**Issue by ajramos27** [Azoft/CarouselLayoutManager#32]
Hi! The carousel is great! I have a question... What do I have to set or change when the distance between each item are very large? I mean, I have a list of items but the height of each one is no too large, it just one textview. But when I implement the layout manager on vertical I get a distance between each one, and I want them to be overloaded.

Thanks :)

**Comment by mig35** [comment]
Hi @ajramos27.
Please give me a screenshot. Any way I think this is similar to: https://github.com/Azoft/CarouselLayoutManager/issues/34
