### ISSUE TITLE
Disable Zooming effect while scrolling when Zooming is enabled

### ISSUE THREAD

**Issue by saisasanksunkavalli** [Azoft/CarouselLayoutManager#35]
Im using the following line to enable the zoom effects ,  `layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());`. The problem with this , even when I am scrolling , every item is getting zoomed when it comes to center , which I feel is distracting the user. How to remove this effect while scrolling ? 

Regards,
Sasank

**Comment by mig35** [comment]
@saisasanksunkavalli 
Not sure if you can do this. You can write custom CarouselZoomPostLayoutListener and somehow detect RecyclerView state.
This is not library issue.
