### ISSUE TITLE
Make childs bigger

### ISSUE THREAD

**Issue by canberkcakmak** [Azoft/CarouselLayoutManager#39]
Hi, thanks for perfect library. I hava a problem about childs.  Here is my implementation : 

  layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());
        layoutManager.setMaxVisibleItems(4);

```

        recyclerView.setLayoutManager(layoutManager);
        // we expect only fixed sized item for now
        recyclerView.setHasFixedSize(true);
        // sample adapter with random data
        recyclerView.setAdapter(adapter);
        // enable center post scrolling
        recyclerView.addOnScrollListener(new CenterScrollListener());
```

here what i want to do : [ios photo](https://i.imgsafe.org/f979fb3e89.png)

here what i do : [android](http://i.hizliresim.com/PnVlE5.png)

how can i make bigger these childs? thank you

**Comment by Kisty** [comment]
I think you may need to make a new `PostLayoutListener`. Try copying the `CarouselZoomPostLayoutListener` and replace `atan` with `sin` instead and experiment.

The `atan` function is used only as a methoematical equation to make centre things large with slower changes and things on the side to small with faster changes

**Comment by canberkcakmak** [comment]
Thank you. I change something but this items too much under of rectangle. How can i push up this ?

[new](http://i.hizliresim.com/adAYpO.png)

**Comment by Kisty** [comment]
Hmm, think you may need to add a number to the coefficient of the `sin(...)` like `0.8*sin(...)`. Essentially, you may have to play about with different values.

See here http://www.wolframalpha.com/input/?i=0.8*sin(2x)

It might be worth investigating how to control sin graphs. Essentially, all it's doing is making the values a bit bigger in the centre and smaller in the middle. The `atan` function gives a fast change from big to small, while the `sin` graph makes it more a gradual change.

**Comment by Kisty** [comment]
Or perhaps `x^2` would suffice. Wouldn't drop off as sharp.

See http://www.wolframalpha.com/input/?i=x%5E(2)

```
final float scale = StrictMath.pow(itemPositionToCenterDiff, 2);
```

**Comment by mig35** [comment]
Hi @Kisty and @canberkcakmak. Sorry for not responding, but I really don't have free time to look into this things. May be I'll have some time soon, but I'm not sure.
Best wishes, Mike.

**Comment by ajramos27** [comment]
scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff/3) + 1.0) / Math.PI + 1)); 
It worked for me :)

**Comment by sergiobr** [comment]
Hello everybody,

I am using at now the canberkcakmak's code. But sincerely I need some help to understand it.
I have been changing it since I got a good scrolling. But when I do that, the cards behind my carousel of cards does not stays as i need.

What I have now it this: [https://i.imgsafe.org/17ef835a9d.png](url)
I have 5 cards but I need to show only one above and below and scroll infinitely: [https://i.imgsafe.org/1813aa30ca.png](url)

I dont understand how the function that calculates the scale works and how it interfers both in size and scrooling.

Thank you

**Comment by canberkcakmak** [comment]
@sergiobr hi, actually in my new project i want to what you say. It's really hard to understand. In my next days i'm looking it ( one below one) maybe  i found  something.

**Comment by sergiobr** [comment]
Thank you

**Comment by canberkcakmak** [comment]
Hi @sergiobr  i think this is not clear for me and i found another library to change something. this is horizontal but really clear. have a nice day. [here](http://tech.leolink.net/2013/02/create-simple-infinite-carousel-in.html)

**Comment by sergiobr** [comment]
Thank yoi @canberkcakmak .
Sorry my english.

**Comment by davidtps** [comment]
scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff/**5**) + 1.0) / Math.PI + 1));
It worked for me :)
