### ISSUE TITLE
Add 10 images in adapter using this library

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [Azoft/CarouselLayoutManager#40]
Hi Author,

I have downloaded 10 images from internet and i need to use this carosel for them. How to do so?

Alsoi need to open new activity on clicking any item of the carosel. Please help me in this.

Thanks

**Comment by Kisty** [comment]
Hi! I'm not the author of this project but I may be able to help.

This library uses a `RecyclerView` to show a list of items. You will have to make a `RecyclerView.Adapter` to tell the `RecyclerView` what you want to display. Have you made an app with a simple list using `RecyclerView` before? If not I'd suggest you do a simple text list of something, say countries. Check out this page to get started.
https://developer.android.com/training/material/lists-cards.html#RecyclerView

As for starting a new activity, you would set an `OnClickListener` on the item with a line like the following:

    startActivity(MyFirstActivity.this, new Intent(this, MySecondActivity.class); 

How new are you to Android development? If you're completely new, I'd suggest that you go through some tutorials first. Walk before you can run. It much easier to get the basics done first, then to try and build upon the that.

I'd suggest the Google Android Udacity course. It's free to watch the videos but to have a certificate, you pay for a plan. Would highly recommend it.
https://www.udacity.com/course/new-android-fundamentals--ud851

Hope this helps!

**Comment by manpreetsinghsodhi** [comment]
Hi Kisty, its not working for me. My recycler view is working fine as a gallery in vertical direction. But when i included the code of this library for that recycler view , it is displaying nothing, not even my gallery list of images.

Here is my code

```
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import com.azoft.carousellayoutmanager.CarouselZoomPostLayoutListener;
import android.support.v7.widget.RecyclerView;

import com.azoft.carousellayoutmanager.CarouselLayoutManager;
import com.azoft.carousellayoutmanager.CenterScrollListener;
import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {

    private String TAG = MainActivity.class.getSimpleName();
    private ArrayList<Integer> images;
    private GalleryAdapter mAdapter;
    private RecyclerView recyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        images = new ArrayList<>();
        final CarouselLayoutManager layoutManager = new CarouselLayoutManager(CarouselLayoutManager.HORIZONTAL, true);
        layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());
        recyclerView = (RecyclerView) findViewById(R.id.recycler_view);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize(true);
        mAdapter = new GalleryAdapter(getApplicationContext(), images);


        recyclerView.setAdapter(mAdapter);

        recyclerView.addOnScrollListener(new CenterScrollListener());
        images.add(R.drawable.bourne);
        images.add(R.drawable.bvs);
        images.add(R.drawable.cacw);
        images.add(R.drawable.deadpool);
        images.add(R.drawable.doctor);
        images.add(R.drawable.hunger);
        images.add(R.drawable.xmen);



    }


}
```

**Comment by Kisty** [comment]
Hmm, thanks for the code. I think if you add the images to the ArrayList *before* you create the the adapter, you might see it correctly. 

Hope this helps.

**Comment by manpreetsinghsodhi** [comment]
Tried this. Still not working for me.

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        images = new ArrayList<>();
        final CarouselLayoutManager layoutManager = new    CarouselLayoutManager(CarouselLayoutManager.HORIZONTAL, true);
        layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());
        recyclerView = (RecyclerView) findViewById(R.id.recycler_view);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize(true);
        images.add(R.drawable.bourne);
        images.add(R.drawable.bvs);
        images.add(R.drawable.cacw);
        images.add(R.drawable.deadpool);
        images.add(R.drawable.doctor);
        images.add(R.drawable.hunger);
        images.add(R.drawable.xmen);
        mAdapter = new GalleryAdapter(getApplicationContext(), images);
       recyclerView.setAdapter(mAdapter);
       recyclerView.addOnScrollListener(new CenterScrollListener());
  }

**Comment by Kisty** [comment]
Hmm, try match_parent on ImageView height?

**Comment by manpreetsinghsodhi** [comment]
Tried. Still not working. Any other idea how can i fix this?

**Comment by Kisty** [comment]
Try downloading the images, then putting the files in the `res/drawable-nodpi/` and load the images without Glide just to rule out the problem isn't with Glide.

**Comment by manpreetsinghsodhi** [comment]
I loaded images without glide. Still not working !!!

 holder.thumbnail.setBackgroundResource(images.get(position));

**Comment by manpreetsinghsodhi** [comment]
Finally fixed it .Changed my MainActivity xml to something like this

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"

    tools:context="com.example.manpsing.pepperbot.MainActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="250dp"
        android:layout_centerInParent="true" />
</RelativeLayout>
```
Thanks Kisty for the support. C u soon on other threads mate.

**Comment by Kisty** [comment]
Hey! Glad you've got it working :).

**Comment by ram992** [comment]
Yes there is this issue with this library, I don't know whether it is a bug, but when ever I use variables like wrap_content or match_parent it will not inflate. But will as soon as there is a fixed height to recyclerViews.

**Comment by isarYMB** [comment]
> Yes there is this issue with this library, I don't know whether it is a bug, but when ever I use variables like wrap_content or match_parent it will not inflate. But will as soon as there is a fixed height to recyclerViews.

Can i see your source code?
