### ISSUE TITLE
LayoutManager is not recycling views.

### ISSUE THREAD

**Issue by nachtien** [Azoft/CarouselLayoutManager#41]
The idea of the recycler is to reuse the views, and not actually inflate them again once they've been inflated (similar to the ViewHolder Pattern), but according to our logging, CarouselLayoutManager is not recycling the views.

In the adapter, we added two log calls:
1.  onCreateViewHolder ("onCreate called")
2. onBindViewHolder ("onBind called at position %s")

Attached is our output of the logs:

com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 6
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 7
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 8
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 9
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 10
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 11
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 12
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 13
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 14
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 15
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 16
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 17
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 18
com.example.scroller D/ScrollAdapter: onCreate called
com.example.scroller D/ScrollAdapter: onBind called at position 19

**Comment by shirensong** [comment]
@nachtien, I have the same question. And it will cause OOM if I load items with image .

**Comment by Gounlaf** [comment]
Maybe here? `recycler.getViewForPosition(0)` [CarouselLayoutManager.java#L341](CarouselLayoutManager/src/main/java/com/azoft/carousellayoutmanager/CarouselLayoutManager.java#L341)

**Comment by mig35** [comment]
This was fixed in the latest version
