### ISSUE TITLE
disabling the circular motion of the center item when scrolling.

### ISSUE THREAD

**Issue by erylljoy24** [Azoft/CarouselLayoutManager#44]
i'm using the vertical view for the carousel, but when i scroll the items, the center will kinda look jerky/jumpy its a bit circular transition, My code below

@Override
    public ItemTransformation transformChild(@NonNull View child, float itemPositionToCenterDiff, int orientation) {
        final float scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff) + 1.30) / Math.PI + 1));

        // because scaling will make view smaller in its center, then we should move this item to the top or bottom to make it visible
        final float translateY;
        final float translateX;
        if (CarouselLayoutManager.VERTICAL == orientation) {
            final float translateYGeneral = child.getMeasuredHeight() * (1 - scale) * 2 * .50f;
            translateY = Math.signum(itemPositionToCenterDiff) * translateYGeneral;
            translateX = 0;
        } else {// 0.60

            final float translateXGeneral = (float) (child.getMeasuredWidth() * (0 - scale) / 2f);
            translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral;
            translateY = 0;
        }

        return new ItemTransformation(scale, scale, translateX, translateY);
    }

**Comment by insearching** [comment]
Played around with different values to get perfect scrolling (in my case).
Please check for horizontal scrolling:

`    @Override
    public ItemTransformation transformChild(@NonNull final View child, final float
            itemPositionToCenterDiff, final int orientation) {
        final float scale = (float) (2.2f * (1.4f * -StrictMath.atan(Math.abs
                (itemPositionToCenterDiff) + 1.0) / Math.PI + 1));
        final float translateXGeneral = child.getMeasuredWidth() * (1.8f - scale) / 2f;
        final float translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral / 3f;
        return new ItemTransformation(scale, scale, translateX, 0);
    }`
