### ISSUE TITLE
Only two items in Carousel

### ISSUE THREAD

**Issue by VitaliyKomaniak** [Azoft/CarouselLayoutManager#47]
Hey guys. Thanks for really great lib :) I have a question. I have only two items in view, and right left child is visible. How to put it behind center one, and show it on sides when items count is > than 2?)

**Comment by mig35** [comment]
Hi @VitaliyKomaniak.

You can try to build a custom `CarouselZoomPostLayoutListener` class, but I don't think that this is possible. This library was designed to have 3 or more items.
