### ISSUE TITLE
Scroll not smooth

### ISSUE THREAD

**Issue by Seidak** [Azoft/CarouselLayoutManager#5]
Hello,
first thanks for great job you did on this project!

Secondly. I successfully used your library but now I am experiencing little problem. 

When I try to change text of textview inside OnItemSelectionListener than immediately recyclerview jump to center item and scroll animation is not smooth but is completed immediately. 

Any idea at least for some workaround? So far I postponed changing a text with runnable so if user scroll fast, than he will not experience this jumping.

Thank you!

**Comment by mig35** [comment]
Hi Seidak,
sorry for long answer, I will check this issue in two days.

**Comment by mig35** [comment]
Hi Seidak,
not sure if I fix your issue, but I've just upload 1.1.2 version. Please, check it.

If it doesn't work, please attach simple sample of your problem.
Regards, Mikhail

**Comment by Seidak** [comment]
Hello Mikhail,
I updated your library and I also changed my code, and problem disappeared. I am not sure where was the problem, but it's gone. 

Sorry for late answer and thanks for your help. If I will find out where was exactly the problem I will keep you updated! So far I think it was caused by calling invalidate for the parent of my recyclerview.

Have a good day,
Seidak
