### ISSUE TITLE
Not working in nested RecyclerView

### ISSUE THREAD

**Issue by i-schuetz** [Azoft/CarouselLayoutManager#50]
I have an horizontal `RecyclerView` in which I'm trying to show a vertical carousel. Nothing is displayed.

If I show the same carousel (using the same code - recycler view, adapter, etc) outside of the horizontal `RecyclerView` it works.

And if I use a normal vertical `RecyclerView` (i.e. use `LinearLayoutManager`) in the horizontal `RecyclerView` instead of carousel, it also works (again, same code, I just change the layout manager + the configuration indicated in the readme).

Any ideas...?

**Comment by kandra777** [comment]
i got the same problem!hava you find any solution mate?

**Comment by eduardoyurencb** [comment]
Try to put a static mesuare 
```
android:layout_width="200dp"
android:layout_height="200dp"
```

**Comment by enigmaIam** [comment]
I also tried using this library in a nested RecyclerView and it doesn't work

**Comment by mig35** [comment]
it works for me in the latest build
