### ISSUE TITLE
Speed issue loading first time

### ISSUE THREAD

**Issue by shanishah215** [Azoft/CarouselLayoutManager#51]
Hello, thanks for share this repository. It is perfect drawing UI for my application. 

The only issue I am facing of the speed of loading. It takes 3-4 seconds for first time loading whenever application moves carousel page. (Please note that Carousel loading static cards and images with in application)

Do you have any solution for this? Kindly add me on skype -- mobileapplication

Best,
Shani Shah

**Comment by mig35** [comment]
Hi Shani,

this issue should be fixed in the new versions
