### ISSUE TITLE
Crashing on fast scroll

### ISSUE THREAD

**Issue by prasannaboppe** [Azoft/CarouselLayoutManager#53]
java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{df91eba position=1 id=-1, oldPos=-1, pLpos:-1 tmpDetached no parent}

**Comment by haris15** [comment]
do you find any solution ?

**Comment by mig35** [comment]
fixed in 1.3.2 version
