### ISSUE TITLE
Reverse scroll behaviour

### ISSUE THREAD

**Issue by rohankandwal** [Azoft/CarouselLayoutManager#56]
Hi,

Thanks for the wonderful library. I am using your library to scroll vertically in `RecyclerView`. Is there a way so that I can reverse the scroll direction? I mean the scroll direction will be from top to bottom.

**Comment by mig35** [comment]
Hi @rohankandwal.

Thank you for your issue, but when I did this library, I had to do only infinite scroll and add simple scrolling as an addition. In this case I have never thought about reversing the scroll direction.
It is a good catch and may be I will do this, but I don't know when.
