### ISSUE TITLE
is it posible horizontal mode but another view visible right and left side

### ISSUE THREAD

**Issue by umutkina** [Azoft/CarouselLayoutManager#6]
[like this](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/18363/278779/NAb0J3TUU19EF9t/tumblr_melwhjYQby1r6rtzuo6_r1_1280.png)

**Comment by mig35** [comment]
Hi umutkina.
I've updated sample. We've already have HORIZONTAL support.

**Comment by umutkina** [comment]
Thank you @mig35
