### ISSUE TITLE
How to change the select position not the middle but the first or last visible position?

### ISSUE THREAD

**Issue by foolingdutchman** [Azoft/CarouselLayoutManager#60]
I want to achieve an effect that the select item as the last visible item, but not the middle one how could it be?

**Comment by cyrildavid** [comment]
Do you know how to get the position of the middle one?

**Comment by mig35** [comment]
@foolingdutchman you can try to change `CarouselZoomPostLayoutListener` with you own implementation. All zoom logic is done there. It has strange api and should be rewritten but I'm not sure if I will have any time to do this.
