### ISSUE TITLE
Is it possible to add animation when selection changes?

### ISSUE THREAD

**Issue by nileshpa** [Azoft/CarouselLayoutManager#7]
Thanks for this great library. 

When selection changes item scale & layout position is changed. Is it possible to add animation to make smooth transition? Thanks.

**Comment by mig35** [comment]
Hi nileshpa!

Have you tried using recyclerView.smoothScrollToPosition(position)?

**Comment by nileshpa** [comment]
Thanks for the suggestion, it helped.
