### ISSUE TITLE
Snap to the next item in list?

### ISSUE THREAD

**Issue by asknask** [Azoft/CarouselLayoutManager#70]
I have implemented this with a CarouselZoomPostLayoutListener. Everything is OK but the scrolling can be paused in between two items. I need the one item to always be in center, so if I fling and when the carousel stops, one of the items is centered (and zoomed).

How would I do that?

**Comment by mig35** [comment]
Hi @asknask.
This is not the correct behavior and the item should be centered after the scroll event.
`recyclerView.addOnScrollListener(new CenterScrollListener());` is doing this.
If you have this code line and items are not centered, please give me the full code to reproduce and I will fix this issue.
Before your answer I will close this issue and will open as soon as you confirm the bug and give an example.
