### ISSUE TITLE
Weird scroll issue while using images

### ISSUE THREAD

**Issue by adsonpleal** [Azoft/CarouselLayoutManager#75]
Thanks for the awesome library!

I'm facing a issue when using images inside the items.
You can see the problem in the following links:

Failing: https://drive.google.com/file/d/13BbxwZLrEBkHs2e5OFZ0EkMdxadUCtWK/view?usp=sharing
Working: https://drive.google.com/file/d/1piBVEx3jhLvmiR4MmI2oShtAu_A1FnLl/view?usp=sharing

In both cases I'm using the exact same code (the weird pink view is the ImageView with background color), except that in the working one I'm not applying the URL.

PS: I'm using Picasso to load the images from web (IDK  if that matters).

**Comment by mig35** [comment]
Hi @adsonpleal.

Now I have some time and will look.

Thanks

**Comment by mig35** [comment]
@adsonpleal fixed in 1.2.3
