### ISSUE TITLE
Enable click items, even when scrolling RecyclerView Android

### ISSUE THREAD

**Issue by jpvs0101** [Azoft/CarouselLayoutManager#78]
I need a help.

0
down vote
favorite
Normal behaviour : When we fling scroll recycler view, items will scroll, then tap, RV will stops scroll, not perform item click.

What I need: Stop scroll + perform item click!

Any hacky way?

**Comment by mig35** [comment]
Hi @jpvs0101 
This is not the part of the library. You can try to add your own touch listener and handle this situation.
