### ISSUE TITLE
trying to achieve Right to Left CarouselLayoutManager

### ISSUE THREAD

**Issue by thetnaingmizo** [Azoft/CarouselLayoutManager#82]
Can anyone help to achieve like the following? I have tried and could not make it.
Please help. Thanks in advance.

![ezgif com-optimize](https://user-images.githubusercontent.com/6733922/43068023-bde22eb8-8e9b-11e8-810e-f2b76abab520.gif)

**Comment by mig35** [comment]
Hi @thetnaingmizo 

This is not a part of the lib. You can look how this library is done inside and change its sources to achieve this sort of effects. You will need to change: `generateLayoutOrder` or `fillChildItem`. The goal here is to change current library elevation.
