### ISSUE TITLE
Can't override smoothScrollToPosition when using androidx

### ISSUE THREAD

**Issue by alinberce** [Azoft/CarouselLayoutManager#83]
Everything went fine and I used to override `smoothScrollToPosition` in order to get a smaller speed for scrolling to a position.  I decided to convert to `androidx` as it has beta1 version. After converting this does not work anymore.

Android studio suggests to  `override fun smoothScrollToPosition(recyclerView: RecyclerView, state: RecyclerView.State, position: Int) {` to ` override fun smoothScrollToPosition(recyclerView: android.support.v7.widget.RecyclerView, state: android.support.v7.widget.RecyclerView.State, position: Int) {`

But now the RecyclerView is part of `androidx.recyclerview.widget.RecyclerView`.

Beside that, I get a `Unresolved reference: startSmoothScroll` and I have no idea why.

How to fix this?

**Comment by mig35** [comment]
Hi @alinberce 

I have to create a separate build of this library to support this new `androidx` class structure. I will do this in the nearest future.

Thanks for your report.

**Comment by alinberce** [comment]
@mig35 any update on this?

**Comment by bernaferrari** [comment]
Any progress?

**Comment by mig35** [comment]
should be fixed now
