### ISSUE TITLE
How to increase width after main view

### ISSUE THREAD

**Issue by zadShaikh** [Azoft/CarouselLayoutManager#90]
![untitled](https://user-images.githubusercontent.com/17671398/47503203-99a2e780-d87a-11e8-9ec3-e7f63f43b293.png)

**Comment by mig35** [comment]
@zadShaikh 
you can implement custom CarouselZoomPostLayoutListener and change items as you want. https://github.com/Azoft/CarouselLayoutManager/blob/master/CarouselLayoutManager/carousel/src/main/java/com/azoft/carousellayoutmanager/CarouselZoomPostLayoutListener.java
