### ISSUE TITLE
How to increase alpha value to side item to center item. 

### ISSUE THREAD

**Issue by BhargaviDeviYamanuri** [Azoft/CarouselLayoutManager#91]
I have used this library to show the image slide show i want to add shade for left and right images which i achieved by doing customization code is below

if (-0.5 < itemPositionToCenterDiff && itemPositionToCenterDiff < 0.5) {
            child.setAlpha(1f);
        } else {
            child.setAlpha(0.5f);
        }

But i want the shade effect as increasing and decreasing smoothly.
any one can help me.
See the attached gif to clear understanding.
![animation](https://user-images.githubusercontent.com/30333222/49818950-1db51e00-fd9a-11e8-9703-0379af5f5f3f.gif)

**Comment by mig35** [comment]
@BhargaviDeviYamanuri Hi there.

You can do this by changing the code in CarouselZoomPostLayoutListener. So extend or create your own implementation and do alpha change near the translation and zoom changes.
