### ISSUE TITLE
Disable interaction for items which are not in center

### ISSUE THREAD

**Issue by alinberce** [Azoft/CarouselLayoutManager#92]
Given a layout that has items with interactive views (Buttons for instance), the user can tap on buttons which are not in the centered item. How could I disable interaction with other views beside the centered one?

![git_carousel](https://user-images.githubusercontent.com/3410575/51039748-91776000-15be-11e9-869a-246bf0bfa332.png)

**Comment by mig35** [comment]
@alinberce yep this is true.
You can manually do this by listening for current center item by OnCenterItemSelectionListener and disable buttons that are not on center.
