### ISSUE TITLE
Fixed distance between items while scrolling ?

### ISSUE THREAD

**Issue by pravinglrm** [Azoft/CarouselLayoutManager#93]
How to make sure that if setMaxVisibleItems=1 then while scrolling items should not overlap each other? There should be at least some distance between items while scrolling and even items are not in moving state.
Something like - yarolegovich/DiscreteScrollView

**Comment by mig35** [comment]
hey @pravinglrm 
If I understand you correctly this behaviour is not supported. You will have overlap anyway.
